- hosts: web-servers
  become: yes
  tasks:
    - name: with_itemsで複数varを処理
      debug:
        var: "{{item}}"
      with_items:
        - "item1"
        - "item2"

    - name: whenでif文的なこと（true）
      debug:
        var: true
      when: true

    - name: whenでif文的なこと（false）
      debug:
        var: false
      when: false

    - name: yumでrpm -i
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
        state: present

    - name: yumでnginxをinstall
      yum:
        name: nginx
        state: present

    - name: templateでファイルをローカルからデプロイ
      template:
        src: config/nginx/index.html
        dest: /usr/share/nginx/html/index.html

    - name: statでファイルの存在確認し、registerで結果を保存
      stat:
        path: /etc/init.d/nginx
      register: result_nginx

    - name: debugでstatの結果を表示
      debug:
        var: result_nginx
