- name: create user1
  user:
    name: user2
    password: "{{user1_password | password_hash('sha512')}}"

- name: create user2
  user:
    name: user1
    password: "{{user2_password | password_hash('sha512')}}"
