- name: add mysql5.6 repo
  yum:
    name: http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
    state: present

- name: yum install mysql
  yum:
    name: mysql
    state: present

- name: yum install mysql-devel
  yum:
    name: mysql-devel
    state: present

- name: yum install mysql-server
  yum:
    name: mysql-server
    state: present

- name: yum install mysql-utilities
  yum:
    name: mysql-utilities
    state: present

- name: start mysql5.6
  service:
    name: mysqld
    enabled: yes
    state: started
