- name: add epel repository
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    state: present

- name: install open vm tools
  yum:
    name: open-vm-tools
    state: present

- name: start open vm tools
  service:
    name: vmtoolsd
    enabled: yes
    state: started

- name: yum update
  yum:
    name: '*'
    state: latest
  when: (do_yum_update | default("yes") == "y") or (do_yum_update | default("yes") == "yes") or (do_yum_update | default("yes") == "Y") or (do_yum_update | default("yes") == "YES")

- name: reboot system
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  when: (do_yum_update | default("yes") == "y") or (do_yum_update | default("yes") == "yes") or (do_yum_update | default("yes") == "Y") or (do_yum_update | default("yes") == "YES")

# - name: wait for ssh port down
#   wait_for:
#     host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
#     port: "{{ ansible_ssh_port }}"
#     state: stopped
#     timeout: 60
#   delegate_to: 127.0.0.1
#   become: false
#   when: (do_yum_update | default("yes") == "y") or (do_yum_update | default("yes") == "yes") or (do_yum_update | default("yes") == "Y") or (do_yum_update | default("yes") == "YES")

- name: wait for ssh port up
  wait_for:
    host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
    port: "{{ ansible_ssh_port }}"
    state: started
    delay: 40
  delegate_to: 127.0.0.1
  become: false
  when: (do_yum_update | default("yes") == "y") or (do_yum_update | default("yes") == "yes") or (do_yum_update | default("yes") == "Y") or (do_yum_update | default("yes") == "YES")
