- name: add epel repository
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    state: present

- name: libselinux-python install
  yum:
    name: libselinux-python
    state: present
